# Generated by Django 3.2.15 on 2024-01-09 13:48

from django.db import migrations

def fill_order_items_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for order_item in order_items.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_items_prices),
    ]
