# Generated by Django 3.2.15 on 2024-01-15 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('lat', models.FloatField(blank=True, verbose_name='широта')),
                ('lon', models.FloatField(blank=True, verbose_name='долгота')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
    ]
