# Generated by Django 3.2.15 on 2024-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20240109_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Принят'), (1, 'Собирается'), (2, 'В пути'), (3, 'Получен')], db_index=True, default=0, verbose_name='статус'),
        ),
    ]
