# Generated by Django 3.2.15 on 2024-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20240114_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Картой онлайн'), ('by card', 'Картой при получении'), ('cash', 'Наличными при получении')], db_index=True, default='cash', max_length=7, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in process', 'Собирается'), ('in delivery', 'В пути'), ('received', 'Получен')], db_index=True, default='accepted', max_length=11, verbose_name='статус'),
        ),
    ]
