# Generated by Django 3.2.15 on 2024-01-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, default=0, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, default=0, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
