# Generated by Django 3.2.15 on 2024-01-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'lon')},
        ),
    ]
